### PR TITLE
refactor(server): links routes and logic

### PR DESCRIPTION
**Pull request by Adezandee**
Hello @lyrgard,

I'm willing to contribute to this project by improving the existing code, using my current experience with Node.js projects.
Here, I refactored a small part of the server logic to improve readability and separation of concerns. Is this kind of work of any interest for you ?

Let me know :)

### CODE REVIEW

**Comment by lyrgard** [comment]
First, I'm all for this sort of cleaning/refacto and ready to integrate you PL.

However, when trying your code with a locally running node server, I got the following exception when trying to log in with google : 

TypeError: oauth2Client.setCredentials is not a function
    at getDriveConfigClient (/home/lyr/dev/sources/ffbeEquip/server.js:188:18)
    at getFileFromGoogleDrive (/home/lyr/dev/sources/ffbeEquip/server.js:145:29)
    at /home/lyr/dev/sources/ffbeEquip/server.js:84:9
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at /home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:281:22
    at param (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:354:14)
    at param (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:410:3)
    at next (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/lyr/dev/sources/ffbeEquip/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:317:13)
    at /home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:284:7
TypeError: oauth2Client.setCredentials is not a function
    at getDriveConfigClient (/home/lyr/dev/sources/ffbeEquip/server.js:188:18)
    at getFileFromGoogleDrive (/home/lyr/dev/sources/ffbeEquip/server.js:145:29)
    at /home/lyr/dev/sources/ffbeEquip/server.js:103:9
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at /home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:281:22
    at param (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:354:14)
    at param (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:410:3)
    at next (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/lyr/dev/sources/ffbeEquip/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:317:13)
    at /home/lyr/dev/sources/ffbeEquip/node_modules/express/lib/router/index.js:284:7

**Comment by Adezandee** [comment]
Hi @lyrgard, whoops ! seems like a bug inside `googleapis` package: https://github.com/google/google-api-nodejs-client/issues/869
I'll downgrade one version for the time being, sorry 👍

**Comment by Adezandee** [comment]
I've added some tests

**Comment by lyrgard** [comment]
Merged, tested it and deployed it. It is live now ! Thanks a LOT for your cleaning work.

**Pull request merged**
