### PR TITLE
refactor(server): oauth routes, auth middleware.

### PR DESCRIPTION
**Pull request by Adezandee**
Hi @lyrgard 

Following on the previous PR, here is a refactoring of the OAuth routes.
I've added an `auth` middleware to automatically handle `Unauthorized` response / OAuth client creation attached to `req` obj.

Also switched to encrypted cookie storage for OAuth tokens.
It's a first step, next I'll take care of GDrive interaction

### CODE REVIEW

**Comment by lyrgard** [comment]
Thanks a lot ! Sorry, but I won't have time to study and test that today, and starting tomorrow, I won't have access to my computer for a week. 

So I won't be able to integrate your PR until start of January.

**Comment by Adezandee** [comment]
@lyrgard no problem.

I'd like to enable a continuous integration pipeline with Travis on the project, could you enable it ?
https://travis-ci.com/

**Comment by Adezandee** [comment]
Hello @lyrgard,
I'am still working on this pull request, I'am adding a better configuration mechanism.

**Comment by Adezandee** [comment]
@lyrgard 
Done, please try it and let me know

**Comment by lyrgard** [comment]
Hello,

First, thanks a LOT for what you do. It looks awesome ! I'm currently testing it on my computer, didn't run into any issue at the moment.

I see that all requests are logged. Isn't it a little overkill ? 'dev' is probably not the desired config for it on the production server, right ?

I also saw you needed to add session on the server. Can you explain why this is needed ?

I'm also looking at Travis CI to see if I want to use it.

**Comment by Adezandee** [comment]
Hi,
Yeah, I'll enable logging only for dev environment
It's not a server session, it's a client-session through a cookie based mechanism. It's working exactly the same as before, the only change is that the cookie is encrypted with a server-side secret for enhanced security.

**Comment by lyrgard** [comment]
How do you enable logging just for the dev environment? 

I started activating Travis, I'll let you know when it is ready

**Comment by Adezandee** [comment]
I'll add a configuration option to select the env.
As for Travis, dont bother with the travis.yml file, i'll commit one on
this branch. If you activated it on the repository, its all good.

**Comment by Adezandee** [comment]
@lyrgard 
Here it is, I've added a new configuration settings `env` that can be overridden with the standard `NODE_ENV` env variable (which you should use, aka. `npm start --production`).

**Comment by Adezandee** [comment]
PR is ready, I will not add more because it's big enough :)
next PR will be on drive api routes

**Comment by lyrgard** [comment]
PR accepted, merged, and deployed in production !

No problem so far ! Travis is now happy.

Thanks a LOT for your WONDERFUL contribution !

**Pull request merged**
