### PR TITLE
Units: add rarity jump list

### PR DESCRIPTION
**Pull request by Indigo744**
Hello,

Here I am, with another little QoL change!

A rarity jump list is added at the beginning of the unit list.
I simply use anchor to jump to the rarity.

Here what it looks like:
image

Of course, it's flexible 😉 

image

### CODE REVIEW

**Comment by Indigo744** [comment]
Note that I'll propose a similar PR for equipment type after this PR and #133 are merged.

**Comment by lyrgard** [comment]
It's nice !

Did you check the export as image feature ?  It probably shouldn't be displayed in the exported image ?

**Comment by Indigo744** [comment]
I did not check. Let me run the server and get back to you 😸

**Comment by Indigo744** [comment]
You were right, it is exported! I'll fix it 👍

**Comment by Indigo744** [comment]
Fixed 😺

**Comment by lyrgard** [comment]
Merged ! I changed the order the tags are displayed, the higher rarities probably being the most frequently used, it make sense to put them first.

**Pull request merged**
