### PR TITLE
Test/static formula

### PR DESCRIPTION
**Pull request by Adezandee**
Hi @lyrgard,

I've been wandering inside the frontend code base and I felt like it could use some unit test. I added in this PR some initial setup to test the frontend code "as is" (ie. with global "exports") and a little suite of test for `formula.js` (that's the easiest one hehe).

Hope you'll like it.

### CODE REVIEW

**Comment by Adezandee** [comment]
Also, on another topic are you willing to accept PRs transform small parts of the frontend codebase with [Vue.js](https://vuejs.org/) ?

You already told me that you wanted to go the Angular2 route, but I feel that that's an impossible path to take with the staggering amount of code to re-engineer within the Angular way of doing things.

**Comment by Adezandee** [comment]
The long-term purpose of this kind of unit testing is to create a new unit test each time a user sends a issue.
I was reading this issue https://github.com/lyrgard/ffbeEquip/issues/112 and told myself that this is very valuable information to "copy paste" inside a unit test in order to:
1. fix the problem
2. keep it fixed in the long run

**Comment by lyrgard** [comment]
Hello Adezandee,

Thanks a LOT ! I always wanted to have some test on my tool, it would help so much because it is quite sensible and prone to regression. However, I have little knowledge of js testing library, and never took the time to setup some.

Thanks, seriously !

**Comment by Adezandee** [comment]
@lyrgard 
Glad you liked it ! Have you read the 2 other comments, about Vue.js ?
For now I'll try to add more test, but a little frontend refactoring is itching me :)

**Pull request merged**
