### PR TITLE
Add all inventory

### PR DESCRIPTION
**Pull request by TedChenNZ**

### CODE REVIEW

**Comment by lyrgard** [comment]
Oh, sorry I didn't provide the icon... WE is always busy for me. Your icon is nice.

I looked at the code. Didn't see anything to correct. I'll test it soon and if everything is ok will integrate it.

Thanks.

**Comment by lyrgard** [comment]
Just curious at what happens if the user click on AddAll more than once.

I thought you'd want to add every weapon and accessory twice, and every materia 4 times, when the items don't have a maxNumber (else add it maxNumber of time). What do you think ?

**Comment by TedChenNZ** [comment]
Current functionality: Adds 1 to each equipment/materia you currently DO NOT own.

Is what you want: Add up to 2 of each equipment, and add up to 4 of each materia, (unless there is a maxNumber)?

**Comment by lyrgard** [comment]
I don't have a solid opinion on this matter. What do you think would be the most useful for the users ?

**Comment by TedChenNZ** [comment]
I'm not entirely sure either, but I suppose each time the button is clicked you add 2 of each equipment and 4 of each materia would be useful(not up but rather just 2 or 4, since the unit management tab might mean people want lots of some equipment). How does that sound?

**Comment by lyrgard** [comment]
Sounds good to me. If you think it'd fulfil your need, it should also fulfil the need of others too ;-)

Also, I create a Discord server for FFBE Equip, it may be easier to discuss there, if you want : https://discord.gg/rgXnjhP

**Comment by TedChenNZ** [comment]
Sorry for taking so long, been pretty busy these past 2 weeks with the holidays and all.

**Comment by lyrgard** [comment]
Finally I'm back at home and had the time to merge it ! It is live !

Thanks a LOT for your work on this !

**Pull request merged**
