### PR TITLE
Press Escape to reset search box

### PR DESCRIPTION
**Pull request by Indigo744**
Hello,

Another QoL update, for the search box this time.

Simply press ESCAPE anywhere on the page to reset the searchbox.

This is something quite usual with search form.

Hope you like it.

### CODE REVIEW

**Comment by lyrgard** [comment]
What would be cool would be to put the focus back on the text box as well when ESC is pressed, to allow to immediatly search something else. What do you think ?

**Comment by Indigo744** [comment]
Good idea! I'll add it ASAP.

**Comment by Indigo744** [comment]
Done as requested.

I've also added this feature for the Encyclopedia and Unit Search page. That way, the behavior is the same for all search box.

**Comment by lyrgard** [comment]
Merged ! Thanks !

**Pull request merged**
