### PR TITLE
Added titles for the ATK and MAG caps

### PR DESCRIPTION
**Pull request by biovenger**
I hope it makes it easier to understand. I've seen this question pop up, and I've asked myself it many times. Only yesterday people were talking about it in discord.

The text/phrasing is just a suggestion, there might exist better terminology.

### CODE REVIEW

**Comment by lyrgard** [comment]
Only problem I see is that the tooltip will mention both values even if only one is displayed. I would rather modify the title (around lines 370-390) to better reflect what is currently dispalyed.

**Comment by biovenger** [comment]
I changed it now so the title reflects the amount of modifiers displayed

**Comment by lyrgard** [comment]
Could you remove the change made to builder.html, as it is not needed anymore, and only concern ATK and MAG (it could also concern SPR and DEF, even if I never saw it for DEF) ?

**Comment by biovenger** [comment]
Right now it will automatically only modify the title of the stats that have an equipment-increase value greater than 0, isn't that correct? So if we get equipped DEF increase, it will handle the case correctly.

**Comment by biovenger** [comment]
Also, builder.html changes reverted now, sorry didn't catch that myself.

**Comment by lyrgard** [comment]
Thanks !

**Pull request merged**
