### PR TITLE
Add wiki links for units and TMRs

### PR DESCRIPTION
**Pull request by Indigo744**
Hello

This is my first attempts to implements #122

I noticed that the relevant function is already here (`toLink()`).
We just need to call it for the unit's name (and TMR's).

I couldn't test it locally as I didn't complete the OAUTH config yet...
I wish there would be a way to try the server without the state save feature...

I think it should be fine, except maybe for units with looong name, e.g.  `Atoning Dragoon Kain` or `Heavenly Technician Lid`...

### CODE REVIEW

**Comment by lyrgard** [comment]
Thanks a lot ! 

I merged this PR, and modified the code so that : 
- all units will take the same width
- the name will be on two lines if too long.

**Comment by Indigo744** [comment]
Sounds good! 😸 

When do you usually push your changes to your server?

**Comment by lyrgard** [comment]
Usually just after I made something. It's already live ! I like to work on small increments, and to release as soon as possible.

**Comment by Indigo744** [comment]
Indeed! This is cool 👍 

Now I wonder if the blue icon isn't too much visible? I don't know. The designer in me is kinda triggered 🤔

**Comment by lyrgard** [comment]
Well, at first, toLink() wasn't adding an icon,but make the whole text a link. It was a problem because it interfered with a lot of click (for instance, it is natural to click on the name of an item to select it to pin it on a build, but it opened the wiki instead). So I opted for this icon.

As for the blue color, blue is usually the color of links on internet.

It doesn't bother me too much.

**Comment by Indigo744** [comment]
I agree with you on the icon. 
For the color, I'm overthinking it I guess :wink:

**Pull request merged**
