### PR TITLE
Removed all HTML repeated tags using PHP

### PR DESCRIPTION
**Pull request by ramonMontanhes**
If you have PHP enabled on your hosting you can merge this. You have a lot of HTML tags that repeat, so I used 'for' and 'foreach' to clean this repetitions.

Like the last pull I have a live working here: http://oakz.org/ffbeEquip/

If you have a contact, can you send me? I want to help more.

### CODE REVIEW

**Comment by lyrgard** [comment]
Hello @ramonMontanhes,

First, thanks a lot for you interest. 

Second, I don't think I'll accept this pull request (or at least, you'll need to convince me ;-) ). It is hard to refuse some good will, and I know you put some time on it, so let me explain my point of view : 

I'm not again using php, but I won't switch on php just because it make the code a little clearer. Here, switching to php has no advantage for the user, the html file they'll receive will be the same, it would just take a little longer to send it to them (I know, a really really little longer) because it has to be parsed by php. On the server side, it implies a little more cpu work, too. Not a lot, but if a lot of users use the site, this is done every time the page is loaded. 

All in one, I weighted the pro (little more clear code) and the cons (little longer loading, little more CPU usage) and I think the pro is not enough to justify using php.

What is your opinion about it ?

**Comment by lyrgard** [comment]
As for my contact, I'm always connected to Google Hangout. My email is my pseudo here "at" gmail.com

**Comment by ramonMontanhes** [comment]
I can't convince you, with PHP the server take a little more time. So can I use javascript to make this more clean? If so I gonna make another pull without PHP.

**Comment by lyrgard** [comment]
If you find an elegant solution to make it more clean, why not !
The repeated html part doesn't bother me too much. It is mainly static content, I rarely need to modify it.

**Pull request closed without merging**
