### PR TITLE
Save excluded items to google drive

### PR DESCRIPTION
**Pull request by TedChenNZ**
Based on inventory saving code

### CODE REVIEW

**Comment by TedChenNZ** [comment]
Hey @lyrgard let me know if there are any changes you'd like me to make before this gets merged in.

**Comment by lyrgard** [comment]
Yeah, I just need to think a little about it.

One of the point that bother me a little is that I'm not sure every one want to have their excluded items automatically saved. Some may just want to temporary exclude an item because they have another unit using it at the moment. For this reason, I think a "Save" button in the popup that show the list of excluded items would be better suited. What do you think ?

I also need to think about the interaction between that and the "Share builder setup" feature. If I generate a builder setup link with "all equipment" and share it to another person, should it take the saved excluded items of that person into account. This feature allow to generate link to perpetual BiS builds for instance. But if it takes the saved excluded items into account, the result of the link may vary from one user to another.

All in one, how will you use this "excluded items" feature ? It is a way to exclude items used by another unit ? (if that's the case, it can change each time, I don't know if saving it is the way to go). Or a way to fill your inventory by excluding items you don't own instead of inputing items you own ? Or another use case ?

**Comment by TedChenNZ** [comment]
Those are some really good points.

Yes, I think that a save button would be better in that case.

The "Share Builder setup" feature will run into the same problem when sharing builds using items in your inventory right? Though I can see why it can be more of a problem with 'excluded items'.

For me, the main use case of exclusions is because inventory management is a hassle. I suppose using exclusions is a hacky workaround, and a better solution would be improving inventory management. 

For instance, as someone that's played for a long time, I have most items except TMRs and some early event items. For me it would be easier to have all items in my inventory and then remove them as they show up in the builder. Alternatively, possibly something like filtering items and being able to select all of them at a time could make it easier. Eg, show only non-event non-tmr items and select that I have all of them (a select all would be nice). Then show only 3* base TMRs, 4* base TMRs, 5* base TMRs, event items, etc. There just feels like there's a lot of items and materia I need to look through which I believe for most people won't be even close to BiS (eg bronze knife).

**Comment by lyrgard** [comment]
The "Share Builder Setup" basically save the left pane, and upon opening the link restore it and launch a build.

If I want to get a perpetual BiS link, I select a unit, set the corresponding imperil if needed, select "all equipment" then get the Builder Setup link.
But I can use it to help people creating there own BiS for an event. I can select a unit, enter the race and elemental resistance of the boss and select "Only owned equipment". Then get the Builder Setup link. Yes, the result will then vary depending on the user that open the link, but that's exactly the goal ;-)

The saved excluded items is a problem because they would apply to the first case (perpetual BiS) whereas those link are supposed to give the same result to all users. Or we need to find a way to exclude them for those links. But it becomes tricky and not intuitive, I guess. I would like to find an elegant solution.

If you use the excluded items as a mean to prevent the hassle of inputing the items you own, I'd prefer working on simplifying inputting the items you own. Personally, the first time I inputed my inventory, I didn't do it with my game open. I just went throught the list of items and inputed the "important" ones, leaving aside items like bronze knife.
What I can propose you is simply a button to add all items to your inventory. And then, on the "excluded items" list, a button to remove an item from your inventory. This way, you can do your builds with your inventory, exclude items you don't own, and the open the excluded items list and remove them from your inventory. How does it sound ? Do you have a better idea ?

**Comment by TedChenNZ** [comment]
>What I can propose you is simply a button to add all items to your inventory. And then, on the "excluded items" list, a button to remove an item from your inventory. This way, you can do your builds with your inventory, exclude items you don't own, and the open the excluded items list and remove them from your inventory. How does it sound ? Do you have a better idea ?

That sounds good! Would you still want a save button for the currently excluded icons?

**Comment by lyrgard** [comment]
I only want it if there is a strong use case for it. Said differently, why would the user need to save the excluded item, if we exclude the "I find entering my inventory a hassle" use case ?

**Comment by TedChenNZ** [comment]
If we go back to the case where some other unit is using it, there might be a use case. But that might be an argument for some unit management page.

**Comment by lyrgard** [comment]
I'm currently working on a "unit collection" page.

Do you want to modify your code to add the button to add all items to an inventory, and to be able to remove items from inventory from the excluded item list ?

I'm really sorry to refuse your pull request as it is now. I'm really happy you took the time to look at the code and even created an Google API key to make it work on your computer, and it saddens me to not be able to recognize your efforts better... I just want the best for the users, and in its current state, I think your pull request bring more trouble than benefits. 

If you still intend to contribute to this tool, I suggest we discuss new features beforehand, so that this don't happen again.

I insist, I'm really thankful for your interest and your effort !

**Comment by TedChenNZ** [comment]
Hey no worries! It was a nice learning experience on how to use the google api, and you're right to not merge this. I'll close this PR and create new PRS for the following:

1) An 'add all' button in the inventory page placed above the inventory tab things. This will add 1 of everything that isn't already in your inventory. I'm assuming this should come with some form of dialogue yes/no to confirm this is what you want to do.

2) The ability to remove items from your inventory from the excluded items popup.

Would you like these as issues?

**Comment by lyrgard** [comment]
Thanks for your understanding !

1. What I would prefer is a new tab, with an icon like "setting" (cogs) or something to give the idea of "actions", or batch of actions, that don't display the list of item but would display the "Add all" button. For 2 reasons : first, this "add all" button will be rarely used (not that I think the feature is not needed, but a user will probably use it only once and never click on it again) so I don't think it need to be always displayed and take screen estate. Secondary, this will be a convenient place to enrich the page with others buttons, like "Export inventory", or whatever may be needed in the futur.

2. Ok. This button should only be displayed for excluded items that are in the user inventory (so only displayed if the user is logged in)

If you have any question while working on that, feel free to ask them, I'll try my best to answer as quickly as possible.

**Comment by TedChenNZ** [comment]
Any chance you can supply the settings icon?

**Pull request closed without merging**
