### PR TITLE
Combobox evolution

### LINKED ISSUE #105: Strange behaviour on new unit
If you add another unit, the cross to the right of the unit name field doesn't revert to the arrow for the list of units (still reverts after you click on the cross)
And if you added another unit, but you didn't specify the unit name yet, if you switch between another unit (with a name) and back to the new unit, the unit name field is filled with the name of the previous unit

### PR DESCRIPTION
**Pull request by Indigo744**
When looking on how to fix #105, I came to the conclusion that [danielfarrell/bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) was not up to the task (development seems to stall, no new version since a lot of time, lot of issues and PR opened).

I decided to migrate to [Select2](https://select2.org/), a wayy better combobox for jQuery.

It fixes #105 right away.

While I was at it, I decided to use this combobox for the Encyclopedia page. And I added a little image, just for fun.

The lib is now loaded from cdnJS, which will reduce the strain on the server (not much, but still).

List of commits:
- On Builder page, replace bootstrap-combobox by Select2
- On Encyclopedia page, replace normal dropdown by Select2
- On Encyclopedia page, add unit image

image

### CODE REVIEW

**Comment by Adezandee** [comment]
@Indigo744 
You put in quite a lot of frontend work, that's nice 👍 
I really like how things are going towards a more "normalised" frontend code. Good job mate

**Comment by Indigo744** [comment]
@Adezandee thanks a lot mate! I'm trying to... So much left to do! 😺

**Comment by lyrgard** [comment]
I'm sorry for giving you so much work to do ? XD

**Comment by Indigo744** [comment]
Nah it's ok 😸 love to help!

**Pull request merged**
